.TH GENWEBGALLERY 1 "genwebgallery\-0.8" "2008\-06\-23" "genwebgallery"

.SH NAME
genwebgallery \- generates minimalistic web galleries

.SH SYNOPSIS
.B genwebgallery [OPTIONS] PICTURES

.SH DESCRIPTION
.B genwebgallery
Generates a web gallery of mentioned pictures. Only very minimalistic static HTML pages are generated. Copies of the pictures are resized to the defined sizes.
.PP
All generated content goes in a subdirectory which defaults to
.IR webgallery .
Or any other directory specified by \-\-output.
.PP
Files are skipped if resizing is not successful. So it depends on the resize program.
.PP
The
.BR mogrify
tool from ImageMagick, or
.BR resize\-gd
is required.

.B mogrify
is the prefered resizing tool, cause of its (assumed) better quality.
.B resize\-gd
on the other hand has much less dependencies, but still provides everything that's needed here. It is used, if
.B mogrify
is not installed. If none of them is available, the program will abort.

.SH OPTIONS
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program
.TP
.B \-v, \-\-verbose
Outputs more log data
.TP
.B \-o, \-\-output
Specify output directory
.TP
.B \-i, \-\-index
Specify index file
.TP
.B \-t, \-\-title
Specify title of gallery
.TP
.B \-f, \-\-footer
Specify footer text
.TP
.B \-ps, \-\-pic\-size
Specify size of pictures
.TP
.B \-ts, \-\-thumb\-size
Specify size of thumbnails
.TP
.B \-\-overwrite
Overwrites the output directory if it exists without asking.
Without this option, the users is interactively asked what to do.
.PP
See
.B genwebgallery \-\-help
for default values.

.SH EXAMPLES
To create an image gallery as fast as possible, simply call the program with the pictures you want as arguments.
.IP
genwebgallery *.jpg
.PP
The program creates a directory
.I webgallery
which contains a
.I index.html
and each picture in large, small and a HTML for it.
.PP
If you want to customize the output
.IP
genwebgallery \-o holiday2008 \-t "Trip to Hawaii" ~/hawaii08/*.jpg
.PP
Creates a directory
.I holiday2008
which contains a
.I index.html
and each picture in large, small and a HTML for it. All HTML pages are titled with ``Trip to Hawaii''.

.SH EXIT CODE
.TP
.B 1
Any other error
.TP
.B 2
None of the supported image resize programs was found. These are:
.B mogrify
from the ImageMagick tool collection, and
.B resize\-gd
.TP
.B 3
The output directory already exists and the user wanted to keep it.
.TP
.B 4
The output directory already exists and the user wanted it to be deleted, but it was not possible.

.SH BUGS
.B mogrify
fails the conversion of the XCF image format of GIMP, but it exits with 0 anyway. This looks like a bug in the
.B mogrify
program.
As result the image is added to the gallery but it is not viewable.
Other formats might be affected as well.

.SH SEE ALSO
.BR mogrify (1),
.BR ImageMagick (1),
.BR resize\-gd (1).

.SH AUTHOR
genwebgallery and this man page were written by markus schnalke <meillo@marmaro.de>
.PP
Website: http://prog.marmaro.de/genwebgallery
