.TH GENWEBGALLERY 1 "genwebgallery\-0.5" "2008\-06\-04" "genwebgallery"

.SH NAME
genwebgallery \- generates  minimalistic web galleries

.SH SYNOPSIS
.B genwebgallery [OPTIONS] PICTURES

.SH DESCRIPTION
.B genwebgallery
Generates a web gallery of mentioned pictures. Only very minimalistic static HTML pages are generated. Copies of the pictures are resized to the defined sizes.
.PP
All generated content goes in a subdirectory which defaults to 'webgallery'. Or any other directory specified by \-\-output.
.PP
Files are skipped if
.B convert
fails in conversion.
.PP
The
.BR convert
tool from ImageMagick is required.

.SH OPTIONS
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program
.TP
.B \-v, \-\-verbose
Outputs more log data
.TP
.B \-o, \-\-output
Specify output directory
.TP
.B \-i, \-\-index
Specify index file (index.htm)
.TP
.B \-t, \-\-title
Specify title of gallery
.TP
.B \-c, \-\-copyright
Specify copyright notice
.TP
.B \-ps, \-\-pic\-size
Specify size of pictures
.TP
.B \-ts, \-\-thumb\-size
Specify size of thumbnails
.TP
.B \-\-overwrite
Overwrites the output directory if it exists without asking.
Without this option, the users is interactively asked what to do.
.PP
See
.B genwebgallery \-\-help
for default values.

.SH EXIT CODE
.TP
.B 1
Any other error
.TP
.B 2
The required program
.B convert
could not be found. It's probably not installed.
Normally it is provided by the ImageMagick tool collection.
.TP
.B 3
The output directory already exists and the user wanted to keep it.
.TP
.B 4
The output directory already exists and the user wanted it to be deleted, but it was not possible.

.SH BUGS
.B convert
fails the conversion of the XCF image format of GIMP, but it exits with 0 anyway. This looks like a bug in the
.B convert
program.
As result the image is added to the gallery but it is not viewable.
Other formats might be affected as well.

.SH SEE ALSO
.BR convert (1),
.BR ImageMagick (1).

.SH AUTHOR
genwebgallery and this man page were written by markus schnalke <meillo@marmaro.de>
.PP
Website: http://prog.marmaro.de/genwebgallery
